name = "cf-worker-ws-dev"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = true

[vars]
# PROXYIP = "172.232.239.249:587"
UUID = "0ef8cab5-51b6-4214-b2d2-b83586d6adaf"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
